name: Android CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest   # <--- изменили с macos-13 на ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Enable KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y cpu-checker acl
          sudo setfacl -m u:$USER:rw /dev/kvm   # даём доступ к KVM текущему пользователю
          ls -l /dev/kvm
          kvm-ok                                 # должно написать, что KVM доступен
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: pixel_3                        # стабильный профиль
          emulator-options: -no-window -no-snapshot -no-audio -no-boot-anim -no-snapshot-save
          disable-animations: true
          emulator-boot-timeout: 1800
          script: |
            adb wait-for-device
            adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
            adb shell input keyevent 82
            adb shell getprop ro.build.version.sdk
            adb shell getprop ro.product.model
            sleep 5                                # небольшая пауза для стабилизации
            ./gradlew connectedCheck --stacktrace
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/androidTests/